apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-custom-binding
subjects:
- kind: ServiceAccount
  name: default  # Tên ServiceAccount mà Pod sẽ sử dụng
  namespace: external-namespace
roleRef:
  kind: ClusterRole
  name: node-custom-role
  apiGroup: rbac.authorization.k8s.io
