apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-custom-binding-2
subjects:
- kind: User
  name: system:node:k8s-worker-02
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-custom-role
  apiGroup: rbac.authorization.k8s.io
