apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-custom-binding
subjects:
- kind: Node
  name: k8s-worker-02  
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: node-custom-role
  apiGroup: rbac.authorization.k8s.io
