apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment-internal
  namespace: internal-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-internal
  template:
    metadata:
      labels:
        app: springboot-internal
    spec:
      containers:
      - name: app-container-peermarket-be-internal
        image: phanhoang102/peer-market-be:v1.3
        ports:
        - containerPort: 8083
        securityContext:
          privileged: false
        envFrom:
        - configMapRef:
            name: internal-config
            
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service-cluster
  namespace: internal-namespace
spec:
  selector:
    app: springboot-internal
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8083
