apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: external-namespace
  name: restricted-access-role
rules:
  - apiGroups: [""]
    verbs: ["get", "watch", "list"]
    resources: ["pods"]
  - apiGroups: [""]
    verbs: ["get", "watch", "list"]
    resources: ["services"]
