apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-pod-creator-binding-02
  namespace: external-namespace
subjects:
- kind: User
  name: system:node:k8s-worker-02
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: full-access-role
  apiGroup: rbac.authorization.k8s.io
