apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-access-binding
  namespace: external-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: external-namespace
